name: Python CI with SonarCloud
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonar:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies necessary for the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest pytest-cov "dash[testing]" webdriver-manager

      # Install Chromium for headless dashboard testing
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      # Generate a coverage report
      - name: Run tests with coverage
        run: |
          coverage run -m pytest test/  
          coverage report
          coverage xml -o coverage.xml

      # Run dashboard integration tests (without coverage)
      - name: Run dashboard E2E tests without coverage
        run: |
          pytest -s -v test/test_dashboard.py

      # Execute project scan and upload the coverage report to SonarCloud
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=ti-forest-sector-modelling
            -Dsonar.projectKey=TI-Forest-Sector-Modelling_C-Module
            -Dsonar.projectName=C-Module
            -Dsonar.projectVersion=1.0.3
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}